### ISSUE TITLE
Notice Pursuant to the National Cooperative Research and Production Act of 1993-World Wide Web Consortium, Inc.

### ISSUE THREAD

**Issue by jwrosewell** [w3c/AB-public#100]
The Vision for the W3C needs to be limited to fit within the [notice](https://www.federalregister.gov/documents/2023/05/12/2023-10207/notice-pursuant-to-the-national-cooperative-research-and-production-act-of-1993-world-wide-web) World Wide Web Consortium, Inc. provided to the US Justice Department Antitrust Division on 12th May 2023.

The notice does raise questions concerning the suitability of the [W3C Antitrust Guidelines](https://www.w3.org/policies/antitrust), why the World Wide Web Consortium, Inc. is now seeking to limit exemplary damages, and why participants were not informed about the notice. 

The suitability of the notice is yet to be assessed and could usefully be reviewed at the next meeting. @TzviyaSiegman could we invite a member of the Board of Directors to talk us through it?

**Comment by jwrosewell** [comment]
This document limits the scope of the Vision and is fundamental to it. 

As a minimum it will be an utter waste of time to create a Vision that conflicts with the document the W3C used to obtain insurance as all future actions of the W3C that conflict will not be covered by the insurance.

@TzviyaSiegman please can you add this to the agenda for Thursday and remove the "propose closing" label?

**Comment by wareid** [comment]
Having read the document, I'm not entirely sure how what we're doing here and what this filing says are in conflict. Just asking us to "discuss" on Thursday (now two days notice) is unfair, can you please explain why you think this document limits the vision? Or at least some more specific concerns?

**Comment by jwrosewell** [comment]
My request was to ask a member of the Board of Directors to talk us through the background to the document and the construction of the notice as they see it.

I see the following as important.

1. The notice is much more positive and concise than the current Vision draft.
2. "neutral forum" is important and steers us away from anything that favors one group over another. That is the subject of a parallel issue. I believe a statement to the US Justice Department Antitrust Division for the purposes of gaining insurance and limiting exemplary damages significantly outweighs language that is discriminatory around harms or who gets to access what data.
3. "standards", "interoperable", "data sharing", are all components of the notice. I would like to see more made of these facets, and less ideology. 

Understanding the Board of Directors position on this would be helpful IMO.

If no one else agrees and everyone else believes the document is irrelevant then as a minimum understanding how the Board of Directors see the Vision interacting with the notice will be helpful.

**Comment by wareid** [comment]
Thank you for elaborating. Just so I can fully understand here, what do you mean by "less ideology"? I think the facets you mentioned are already reflected in the vision and associated documents, unsure about the rest.

**Comment by michaelchampion** [comment]
> "standards", "interoperable", "data sharing", are all components of the notice. I would like to see more made of these facets, and less ideology.

It also says "(c) ensure that all foundational Web technologies meet the needs of civil society, in areas such as accessibility, internationalization, security, and privacy; "  What "ideology" is in the current Vision draft that isn't covered by that list?  In any event, the list is introduced with "such as"  so clearly not meant to exclude something not mentioned, so long as it would "meet the needs of civil society".  Avoiding harms related to who gets access to what data is an obvious need of civil society even if we might disagree about what specifically is harmful and whether specific harms outweigh supposed benefits.

> My request was to ask a member of the Board of Directors to talk us through the background to the document and the construction of the notice as they see it.

@jwrosewell that sounds like a topic one might suggest for the upcoming AC meeting, it doesn't seem appropriate for a Vision Task Force meeting.  There is a member-only AB issue soliciting AC meeting suggestions, that would be a more appropriate venue for this matter. 

I agree with whoever added the "Propose Closing" label. This is not in scope for the Vision TF, even if other members besides @jwrosewell would like to discuss the implications of the Notice with the W3C Management and the Board.

**Comment by cwilso** [comment]
If your intent is to understand the Board of Directors' opinion on something, you should ask the Board of Directors.  As such, I would recommend starting a discussion on https://github.com/w3c/board/discussions rather than here.

Fwiw, I would point to several things here:

- The Notice describes the W3C's work to "provide a neutral forum where organizations around the world come together to create the technologies to most fully realize the potential of the Web", but does not (as is seemingly implied) claim that every technology thus created adheres to every other meaning of the word "neutral".  (Indeed, as the vision currently states, " Technology is not neutral; new technologies enable new actions and new possibilities, and we must take responsibility to address the impacts of the Web."
- Both standards and interoperability are already deeply part of the Vision.  "Data-sharing" is mentioned once in the Notice: "[The W3C will work to] foster a consistent architecture accommodating the rapid pace of progress in Web standards for websites, browsers, data-sharing applications, and devices to experience all that the Web has to offer".  This does not appear to conflict with any part of the vision work.

As I do not believe the Notice and any of the Vision work are in conflict, I would support closing this issue.

**Comment by jwrosewell** [comment]
I have asked the Board of Directors directly via issue [Board issue #53](https://github.com/w3c/board/issues/53) and will close the issue here.
