### ISSUE TITLE
"supports truth over falsehood" may read like censorship

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/AB-public#113]
As I [noted in a separate review](https://github.com/w3c/AB-public/pull/103/files#r1291521220), I'm uncomfortable with the phrasing that the Web should "support truth over falsehood" (initially introduced in https://github.com/WebStandardsFuture/Vision/pull/36 ) - this can easily be read that we would be OK with introducing mechanisms that prevent "falsehoods" from being published (which of course then raise the question of who determines what is true, and the associated risks of censorship).

My sense is that societies have developed mechanisms to deal with the harms caused by the spread of falsehoods for a long time; the issues that the Web has created in that space is that it has made it much easier to defeat these mechanisms without creating sufficient room for replacements. I'm not sure how to phrase it while retaining the punch that https://github.com/WebStandardsFuture/Vision/pull/36 was seeking, but I don't think the current phrasing is right either.

This probably relates to #13

**Comment by swickr** [comment]
"that allows truth to travel as fast, or faster than, falsehood"

**Comment by mnot** [comment]
I'm not sure the PR is any better -- this smells like we're making ourselves feel better, not actually delivering a more fact-filled Web. Given that many see the Web as failing precisely in this area, shouldn't we get some 'runs on the board' before making such bold claims? At the least, we should acknowledge that the Web fails this test so far, and we don't have any clear path to changing it yet.

**Comment by dontcallmedom** [comment]
"facts over falsehoods" reduces the censorship connotation, but doesn't really address the point I was (not very clearly) trying to make.

"facts over falsehoods" (and likely "people over profits", "humanity over hate") are priorities that are made by societies, within their own governance systems. The Web has broken or weakened many of these governance systems because of its scale and the challenge of enforcing some of the governance mechanisms. I think our vision is to make it so that our technologies are built to enable ethical governance mechanisms to be operative; I'm not sure simplifying some of these trade-offs in a set of (certainly punchier) comparisons can properly express that.

(to take an example of why I'm wary of simple statements in that space - "facts over falsehoods" means parody (often based on complete intentional falsehoods) should be harder to spread than factual but highly biased data - is that so?)

(I'm less concerned in this particular issue with @mnot 's point that we aren't effective at all in fixing this - one could argue that recognizing the problem is a necessary first step to fixing it)

**Comment by darobin** [comment]
A fact is "a thing that is known or proved to be true." This change doesn't address the problem of implying that there is one universal truth and a way to know it, but obscures it by indirection. I think this principle two problems: first, it is suspect from epistemological, ethical, and political angles, and second we don't have any clear way of making it concrete and holding ourselves accountable to it.

**Comment by cwilso** [comment]
Dang it, was trying not to close.

**Comment by dwsinger** [comment]
I think there is a misunderstanding here. we're not saying we'll make a garden of pure flowers of truth and no weeds of falsehood. We're saying that _when_ we have a design choice, if one direction makes the propagation of falsehood easier and the other makes truth easier, we prefer the one that favors truth. And there are such choices.

**Comment by darobin** [comment]
I think it might help if we had examples of what people here think such choices would look like, what concrete work it would start, change, or stop. Given that this is a principle that doesn't map to any enforcement structure that we have, it's hard to know if any two people here are in consensus about what it means, there's no reference. I can certainly think of things we could do to help the web become a healthier information ecosystem but it's not clear to me that there's alignment on this topic or that we'd have the political capital to make them happen if there is.

**Comment by cwilso** [comment]
I would like to be very clear that this sentence is intended to be an aspirational statement; it is not a principle.  It is not something that we will achieve all at one go, or a mandate; as David said, it should be a high-level preferential guide.

**Comment by mnot** [comment]
@cwilso understood, but it needs to be clear in the document, not hear -- we need to consider that readers may not be predisposed to give us the benefit of the doubt.

**Comment by wareid** [comment]
Considering it's placement in the introduction, the general "pithyness" of the phrasing, and that we further elaborate on details later in the document of what we intend to do and how, I think we can give our audience a little bit of good faith here.

**Comment by dontcallmedom** [comment]
To give some context on the perspective I'm trying to read the document through: I've volunteered to take a first stab at mapping the Vision document to the current W3C and the directions it would need to take to better fulfill this vision.

It sounds from what I'm reading that I should ignore the Introduction in that effort; but if so, it looks like some of the strongest statements become the least impactful ones. And in particular, it looks like the question of misinformation only surfaces via the EWP; that may be OK, but I find the gap between the intent expressed in the introduction and the rest of the document a bit misleading.

**Comment by cwilso** [comment]
I do not have a strong idea of what is being suggested here.

**Comment by chaals** [comment]
It's not obvious how we might apply this principle in general. There are specific things we work on that touch on this, such the "web of trust" as an idea, VC and DIDs underpinning concrete technology development, the semantic web as a framework of statements that can be compared.

Should we interpret the statement in the introduction as supporting that work? If so, it seems too weak, and should be reflected in the content of the document.

Do we agree that the Web does not aim to provide for censorship of statements, but does aim to provide a platform where they can be tested and assertions can be matched to assessments of their truth?

**Comment by TzviyaSiegman** [comment]
@dontcallmedom is your request that we more strongly describe that we will work on reducing misinfo?

**Comment by mnot** [comment]
@dwsinger we absolutely should not do that. However, we also need to acknowledge our limitations - we are not (I hope) techno-utopians, and we should make sure we're not misunderstood as such.

I'd be much more comfortable if we added something like:

> We believe the World Wide Web should be inclusive and respectful of its users: a Web that supports facts over falsehoods, people over profits, humanity over hate. Although we acknowledge that technical standards cannot fully address inherently social issues, we will use what influence they do have to enable a better Web for its users.

**Comment by darobin** [comment]
@mnot While I agree that we need to be honest about the limits of technical standards, I don't think that acknowledging that here solves the problem. Supporting "facts over falsehoods" is a _very_ loaded proposition. Is religion factual? Are political opinions factual? Is the multiversal interpretations of physics factual (because it "follows the maths")?

The reason it reads like censorship is because it implies that there is some sort of universal frame of reference that both 1) exists and 2) is accessible to humans to distinguish fact from falsehood. Some people have posited that such a frame exists — but… it's a metaphysical belief, there's nothing factual about it. The statement comes across as censorship because this metaphysical commitment is censorship-friendly. (It's the "facts don't care about your feelings" branch of rationalism.)

Taking a step back, I think that part of the problem is that this is formulated as complete abstractions (facts, falsehoods) rather than as something that applies to people. Recognising that this isn't the formulation that would work for the document, I think that the intent under the sentence is to support resilient epistemic communities[0][1]. That is IMHO a very worthy goal and and also something that we can design technological architectures to support (e.g. anything that supports social media in being many smaller communities rather than a big mosh pit, that encourages as much editorial diversity as possible in writing and in search, anything that can help flow money to what people find interesting rather than to what someone else can measure as relevant). Starting from first principles about what's good for society, that's something you'd definitely want.

The thing is, however: any thriving world of diverse epistemic communities is going to be filled with statements and beliefs that you would be hard-pressed to consider factual. It will also contain many convenient falsehoods that do good in the world simply because they work. It will also have a lot less (harmful) misinformation.

I don't have a catchy line for "the web should foster resilient epistemic communities." It could well be that the closest would be "the Web should not help misinformation thrive" or something that's directly about misinfo, since that appears to be the underlying intent. What's certain is that "facts over falsehood" — the general belief that you can have a single source of relevant facts for everyone and the single unified identity that goes with it — is a big part of what brought us here. We don't want more of it.

[0]: https://www.cambridge.org/us/academic/subjects/life-sciences/natural-resource-management-agriculture-horticulture-and/principles-building-resilience-sustaining-ecosystem-services-social-ecological-systems?format=HB&isbn=9781107082656
[1]: https://www.mdpi.com/1099-4300/24/4/476

**Comment by mnot** [comment]
Also, further up:

> We must do better. We must take steps to address these consequences in the standards we create.

... leads the reader to think we believe we can solve everything with standards and technology. This needs to be contextualised, or removed.

**Comment by dwsinger** [comment]
Not sure how you equate taking steps with solving everything. Look, it is supposed to be an inspiring description of our values and vision, not an essay or specification that carefully contextualizes and conditions every nuance. That is for the next level of document.

**Comment by mnot** [comment]
It's going to be read by people who want to be inspired, but it's also going to be read by people who are critical of tech bros (or those perceived as such) thinking they can change the world to their whim. 

This is even more so in the context of things like [this](https://a16z.com/the-techno-optimist-manifesto/) being part of the culture. 

We need to be deliberate and clear about our intent, not rely on charitable reading of lofty prose to get us through.

**Comment by dwsinger** [comment]
I am finding this quite puzzling. There are two trends here that the document pretty clearly separates us from:
* techno-neutrality: the idea that technology is neutral, is orthogonal to values, and has no effect on social issues (positive or negative)
* techno-utopianism: the idea that technology has a wonderful positive effect but absolutely no negative effects

It's true, technology doesn't change human nature – people have always twisted things or lied, if it's to their advantage, for example. But technology *has* amplified some social problems.

So, I also reject, with these two, techno-nihilism: the idea that there's nothing that can be said or done by those developing new technology, that they can do nothing about the societal problems that that technology might or does amplify.

@mnot your criticism above seems to say that we're engaging in techno-neutrality or techno-utopianism when the thrust of the document is quite the opposite. 

Rather than watering down the vision, perhaps we need to strengthen the context: 

"We reject the idea that those developing new technology should give no thought to its impact on society. We also reject the idea that the problems are simply technical ones, amenable to solution by technologists; we have a part to play, but these are human and social problems and mitigating them will require broad-based action across all of society, not just the technology fora."

**Comment by mnot** [comment]
That would be an improvement, although it has a somewhat strident, I'm-writing-a-manifesto tone.

**Comment by mnot** [comment]
BTW, my criticism isn't about the nature of what we are or are not doing. My criticism is that we need to do an adversarial reading of the document, to anticipate how it will be understood and misunderstood by people outside the consortium -- especially those who may not be predisposed to be 'on board' with what we do.

**Comment by mnot** [comment]
Reading the most recent TF minutes, it doesn't appear that my input is being considered seriously, and indeed those minutes read like an object session in group-think. So I won't be giving any more feedback at this stage.

**Comment by cwilso** [comment]
As per Vision meeting at TPAC: RESOLVED: Close issue 113 as resolved as originally filed, and open a new non-statement-blocker issue forking from relevant comment in summary: "criticism is that we need to do an adversarial reading of the document, to anticipate how it will be understood and misunderstood by people outside the consortium"
