### ISSUE TITLE
Awkward sentence

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#116]
"We create standards with an ethical intent to improve equity of access and participation on the Web. " is awkward and hard to read.  (From @fantasai )

**Comment by michaelchampion** [comment]
It's awkward because the sentence is trying to say several things at once:
- We have ethical intentions
- We are trying to improve equity of access to the web 
- We are trying to improve equity of participation on the web

I'd suggest dropping "ethical intentions".  It doesn't matter whether one's intentions are ethical, what matters is whether the actions and their results are ethical.

I'm not sure it's worth distinguishing equity of access and equity of participation ...

So I'd suggest:  "We create standards to improve equity of  participation on the Web"

**Comment by michaelchampion** [comment]
But looking more closely, the whole bullet point here is pretty much the essence of the Vision:

> We create standards with an ethical intent to improve equity of access and participation on the Web. We will ensure the technical standards of the Web meets broad goals using consistent horizontal review to ensure accessibility, internationalization, sustainability, privacy, and security.

Clearly ethical principles, specifically the TAG EWP, guide implementation of the Vision, so we don't want to just drop "ethical" from the Operational Principles section. 

Maybe consider  re-organizing the whole section a bit, incorporating text from this bullet point to summarize and introduce the detailed bullets. Something like:

The fundamental function of W3C community is to create Recommendations, which are voluntary global technical standards and guidance.     W3C must be a community of diverse voices from around the world and from different organizations and industries, working together to build consensus Recommendations. Our main tool is using consistent horizontal review and community-wide consensus building to ensure Recommendations help ensure the Web's accessibility, internationalization, sustainability, privacy, and security. 

In order to fulfill this function, we will follow these operational principles:

- We put the needs of users first: above authors, publishers, implementers, paying W3C Members, or theoretical purity.
- We intentionally involve stakeholders from end to end in building the Web: developers, content creators, and end users. Our work will NOT be dominated by any person, company, or interest group. It WILL be driven by  diversity and inclusion of participants from different geographical locations, cultures, languages, disabilities, gender identities, industries, organizational sizes, and more. ~~[redundant?] In order to ensure the W3C serves the needs of the entire Web user base, we also strive to broaden diversity and inclusion for our own participants.~~
- Our standards are rooted in a strong royalty-free patent policy and open copyright licenses.
- We welcome individuals and organizations of all sizes (from single-person companies to multi-nationals), and take feedback from the general public.
- We are committed to encouraging research and incubation in new areas, collaborating on innovations across our community.
- We believe proven interoperable implementation is a requirement for broad adoption of standards. To ensure reliable interoperability, we require multiple implementations and open test suites for our standards.
- We aim to reduce centralization in Web architecture, minimizing single points of failure and single points of control.
- We are committed to establishing and improving collaborative relationships with other Internet and Web standards organizations, and building and maintaining respected relationships with governments and businesses for providing credible advice.

**Comment by cwilso** [comment]
@michaelchampion I think it's probably illustrative that you didn't identify what I think is the core point of this bullet: that we use horizontal review to improve these equity axes.  I don't want to reorganize the whole section and lose that point; let me take a stab at just this bullet, and then you can suggest this reorg if it still seems needed.
