### ISSUE TITLE
Horizontal review

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#117]
"using consistent horizontal review" is a specific methodology, not a value.  (per @fantasai )

**Comment by cwilso** [comment]
I agree that consistent horizontal review is a specific methodology, not a value.  That's why it appears as an operational principle - operationally, we will use consistent review, to ensure broad goals in our values of a11y, i18n, etc.  I think this is proper as written.

**Comment by frivoal** [comment]
I think the sentence is reasonable, but the title bugs me a little. What's important about HR is not that it's consistent: you could get consistent review by doing no review at all every time, or just checking for spelling mistakes every time…

Maybe:
* "Deliberate Review": we don't just let anybody review (though we do that do), but we have a intentional plan to review the document on some specific criteria.
* "Cross-Functional Review": calling out that experts from various functions or disciplines participate in the assessment.
* "Interdisciplinary Review": idem
* "In-Depth Review": Emphasizing the depth of examination that goes beyond a surface-level review.
* "Thorough Review": idem

In all cases, Review could be swapped for "Analysis", "Scrutiny", "Evaluation", "Assessment"

You can also take more than one adjective. E.g. "Deliberate Interdisciplinary Scrutiny"…

**Comment by dwsinger** [comment]
how about "widely and publicly reviewed"?

**Comment by frivoal** [comment]
that's not the same though. Horizontal review is a component of wide review, but that particular component is not particularly well described by "wide" or "public".

**Comment by dwsinger** [comment]
I think that widely when paired with publicly like this does imply a wide internal review, and a wide internal review would imply getting input from those in other groups and disciplines. It's a mission statement, not a formal definition.
