### ISSUE TITLE
How to publish, goals

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/AB-public#135]
How can we achieve consensus? What is the goal of publishing a statement? W3.org already features a portion of this at https://www.w3.org/mission/.  How will this be used?
@dwsinger please tell us if the board will use this as is
@koalie and @amyvdh please tell us if the comms team will use this as published.

If the BoD and comms teams will not use the document as this group publishes it, I think we are wasting a lot of time and should publish the draft as a note (not statement) within the next month (November 2023). We can reconvene in the next 6-12 months to assess whether this should be edited and published as a statement.

**Comment by dwsinger** [comment]
I believe that I should be seeking for financial support – the effort I tried a few years ago needs resurrecting. There are various parts of that, but a major reason I contributed to this is that I think a potential funder needs answers to the questions "why do we matter? what are we doing for society? how are we transforming the world?" and so on – our vision, our aspirational goals. There are other things that I need, before I can approach funders, so this is not the only blocking item.

**Comment by michaelchampion** [comment]
I don't think consensus is possible on a forward-looking Vision, W3C's stakeholders have disparate reasons for being here and goals for what they want to pursue.  A statement such s https://www.w3.org/mission/ that is essentially a feel-good statement that smooths over the differences is fine, but that's not the AB's job.  

I agree with @TzviyaSiegman 's proposal to publish the work so far as a Note.  The Board and W3M can use whatever they find valuable in the work so far. Or not.

I've written this a few times before in this repo, but this was my motivation for staying involved in the Vision project after I retired:  In 2020 when the work began, W3C the organization was clearly at an inflection point: Tim had checked out, the Director-Free process was still in the works, the Legal Entity work was underway, and it was increasingly clear that we would be needing new leadership of W3M before long. The Web itself was also at an inflection point: the techno-optimism of the 1990s-2000s was fading fast, fraud and disinformation were out of control and were toxifying real world politics.  (If anyone thinks there's no data to support that, I simply don't know what to say ....).   So the web community needed an "Oppenheimer moment" to reflect on what the web had wrought for good and for bad. A community (I once thought it could be W3C) could study what went wrong, amplify what went right, and "lead the web to its full potential" as a platform for reality-based, human-centered communication.

The last 3 years has been an education for me.  Clearly lots of stakeholders are comfortable with the traditional "technology is value-neutral and always a  net positive" view Marc Andreessen recently doubled down on https://a16z.com/the-techno-optimist-manifesto/ .  Clearly lots of W3C members hope to get investments from Mr. Andreessen and Co. to create the Next Big Thing and displace the current industry incumbents.  Clearly lots of the incumbents' competitors hope to use W3C as a lever in their political and legal fights to displace them.  And sure, the current incumbents mainly want to make the web platform work more smoothly without a lot of drama.   

So W3C is not the right venue to discuss and publish a "manifesto" about what went wrong and how to learn from that.  People will do that elsewhere. W3C will muddle on as it has, doing some  good work, a bunch of ultimately useless work, probably some actually harmful work ... and letting the outside world sort it all out.

**Comment by cwilso** [comment]
I find myself in agreement that the AB should take this back up to publish as a Note (presuming the AB can reach consensus on that).  I do not think that we will reach consensus across the membership on any document that is compelling enough (imo) as a Vision.  

I think the AB should attempt to reach consensus, and hand that output to the Team and the Board as fodder to use for the web site, evangelism/fundraising, and whatever other purposes they may wish.

**Comment by chaals** [comment]
(*my* vision regarding this work is that W3C has 

- a stated vision for the web,
- a stated mission for itself, and
- stated objectives and practices that describe how the organisation carries out its mission to help realise that vision,

and that these have consensus among the W3C membership).

If the AB can't get consensus across the organisation on its idea of the vision, I think publishing it as a Note is a Bad Idea™. I think it's worth the effort to get consensus, and recognise that could take considerable time and effort. If the AB truly believes they cannot reach a consensus among the members on a useful vision, they should simply stop the work.

The AB are meant to represent the members. If there's disagreement between those two bodies on what we are here for, I think that disagreement signals a problem that needs to be resolved.

Publishing an AB Note without member consensus seems likely to antagonise numerous members of the community who think there are real problems in the document published. It also seems likely that in future it would be referred to by others as having some authoritative value as W3C's vision, since it comes from the AB and there isn't an obvious alternative - much as is the case with the Ethical Web Principles today.

However, I am not convinced that we cannot get consensus on a useful sense of our mission and our vision for the web. In addition, the conversations that are necessary to get that consensus seem important to me.

To answer directly the questions posed by the issue:
- The goal is to get rough consensus from the members on what the W3C's vision is, what its mission is, and how it will achieve that mission to realise the vision to the best of its ability.
- "The AB" (i.e. people it nominates) should be managing a thoughtful conversation with the membership, taking careful account of comments and seeking to address the concerns raised by members and resolve disagreements either by finding consensus of the membership on them, or working out how to reflect the divergent opinions in the document. 

Doing this a manner that makes participants feel that the process is effective, and thus gives the W3C community trust in the output, takes time and patience. Balancing the need to make and demonstrate progress with the need to maintain and increase that trust is hard. 

Concretely I think that compared to the way we are working right now we should aim to "hurry up a bit more slowly". Perhaps a useful approach is for the Task Force to work on a document until they are happy, propose it to the membership for review, with the *clear expectation* that review may surface disagreements in the broader community that will need to be discussed again, and repeat that, until we do get to consensus.

It seems to me that
- the Task Force feels it is under pressure to get this finalised quickly, and 
- to a certain extent the TF seems to feel that since anyone is permitted to join meetings it has a mandate to make decisions and those who failed to participate in the TF should not expect to challenge those decisions once made.

I don't think either of those perspectives I am ascribing to "the Task Force" are helpful, so to whatever extent they might be true I think it would be helpful to change that understanding of the AB/TF's mission here.

**Comment by fantasai** [comment]
> If the AB can't get consensus across the organisation on its idea of the vision, I think publishing it as a Note is a Bad Idea™. I think it's worth the effort to get consensus, and recognise that could take considerable time and effort.

I disagree on this one, but only to an extent. I agree it's worth the effort to get consensus in the community at large, but I also think that the AB needs to own this effort and to establish its own consensus first. This is exactly what we do in WGs: we ask for broad feedback on our drafts, and we try to address the issues, but ultimately we publish a CR that represents the WG's consensus as their best effort at a spec.

Similarly, I think the AB needs to address the various issues to the best of its ability, come to consensus on the document among themselves, and publish a Group Note that represents their consensus as their best effort as a Vision. That's what a Group Note is: a document that represents the best efforts of an individual group (in this case, the AB).

From there we can work on creating consensus within W3C, and hopefully develop that towards a Statement. But at least we have a document that is complete and self-consistent, and that a core group of W3C reps believe represents a pretty good effort at describing what W3C is. And that's a much better basis for a broader conversation.

**Comment by chaals** [comment]
@fantasai wrote

> I also think that the AB needs to own this effort and to establish its own consensus first.

I don't think the AB needs to "own" the effort, I think it needs to take responsibility for the effort continuing and reaching a goal. But then, IMHO acceptable goals are "we have consensus among the membership" or "we decide we cannot do this, and don't publish anything", whereas e.g. "the AB publishes a W3C Note it can't get the members to support as a consensus" strikes me as a bad outcome - an "own goal" in sports parlance.

So I don't think the AB needs to establish its own consensus first, and I think that can be harmful as a procedure because it risks the AB then defending its consensus against the membership, instead of working with the membership to establish a consensus. My interpretation of several discussions over the development of this document are that some feel that risk is in fact being realised. I think that even a perception like that is unhelpful to the overall effort.

The difference between this work and what Working Groups typically produce, even groups like WAI E&O or the TAG, is that the vision is a statement of who we are and what we want, rather than just a technical proposal that we can choose to ignore or implement as participants in a market-based ecosystem without prejudice as to whether we think it is the approach we **should** be taking.

**Comment by cwilso** [comment]
The fact that this is not just intended to BE the https://www.w3.org/mission/ leads me to believe we are over-investing in trying to wordsmith the vision document.

**Comment by koalie** [comment]
> The fact that this is not just intended to BE the https://www.w3.org/mission/ leads me to believe we are over-investing in trying to wordsmith the vision document.

I consider /mission/ as a brochure (hence the graphic, video, and big buttons) whereas the vision document to be published on /TR/ to be more formal as a means to specify how decisions are made.

I don't know if my comment helps you wrt assessing whether/how much we are over-investing to wordsmith, but I thought I'd give the rationale.

**Comment by cwilso** [comment]
@koalie I hope you did not take that as a negative statement about https://www.w3.org/mission/; it was not intended as such.  I would certainly expect, in any case, for that page to be more brochure-like in presentation.

My point was that the _content_ isn't the same, either - and to @dwsinger's response of 'a potential funder needs answers to the questions "why do we matter? what are we doing for society? how are we transforming the world?" and so on – our vision, our aspirational goals' - the /mission/ page is answering those questions, with different answers ("Our mission" is different entirely from the doc mission; "Our vision" centers on a tagline (make the web work for everyone) and only includes the vision for the WWW; "our identity" shares a few phrases but introduces others and skips some; design principles are new/radically derived from the EWP; and strategic goals are different.

We had been attempting to craft a concise, targeted vision doc at the same overview level.  The original idea behind what became this doc is that we should have a clear stated mission and principles for the W3C as an organization, building on the principles we believe in for the Web (largely covered by the EWP).  As @chaals put it, 

- a stated vision for the web,
- a stated mission for itself, and
- stated objectives and practices that describe how the organisation carries out its mission to help realise that vision,

and ideally, that that these have consensus among the W3C membership.  There should be one message, one narrative for the W3C.

**Comment by koalie** [comment]
> @koalie I hope you did not take that as a negative statement about https://www.w3.org/mission/; it was not intended as such.

Nope! not at all! We're good. I intended my response to be as I felt it: objective. Sorry if it was dry!

**Comment by koalie** [comment]
> My point was that the _content_ isn't the same, either

I have not updated the content of /mission/ since late July 2023 (just to add a link to the editor's draft of the vision document). The previous overhaul of /mission/ dates back from one of your earlier stable editor's draft but that was 9 months ago I think. Since the Vision doc has been in flux, I've been waiting till it has stabilized to assess just how much of it to reuse in /mission/.

**Comment by cwilso** [comment]
I think we have enough of a plan here to close.  @TzviyaSiegman ?

**Comment by cwilso** [comment]
AB resolved to close because we now have a plan: https://www.w3.org/wiki/AB/VisionTF#Workmode
