### ISSUE TITLE
Include a purpose statement in the vision?

### ISSUE THREAD

**Issue by LJWatson** [w3c/AB-public#153]
During its F2F meeting in January, the Board and the AB Liaisons attended a training course that covered strategy and risk for NFP organizations. I'm sharing some of the notes I took on the basic concepts because I think it might be worth adding another small bit to the vision document:

>An organization's strategy begins with a vision statement. A vision statement articulates the future the organization wants to realise.
>
>A vision statement is accompanied by a purpose statement. A purpose statement articulates what the organization will do to achieve its vision statement.
>
An organization's vision and purpose statements are accompanied by a set of values that describe the behaviours the organization believes are important as it achieves its vision.

To be clear, I do not mention all of this in order to relitigate what is/is not a vision/mission/whatever. I actually think the vision doc has it nailed pretty well.

We were told that the vision statement should be short and aspirational, and I think this captures it: 
>W3C leads the community in defining a World Wide Web that puts users first, by developing technical standards and guidelines to empower an equitable, informed, and interconnected society.

The operational principles seem to be values by another name, but I'm not sure the AB's vision document includes as purpose statement - at least in the sense the Board's training described it?

The training further advised that the purpose statement should be concise, and that it's usually a reflection of what's in the Certificate of Incorporation. Here's the bit from W3C's:
>The specific and primary purpose of the Corporation is to engage in charitable, educational and scientific activities within the meaning of Section 501(c)(3) of the Internal Revenue Code of 1986, as amended, or the corresponding provision of any future United States Internal Revenue Law (the "Code"). The Corporation shall seek global participation in carrying out its mission, which it shall endeavor to conduct through the activities of its global team, membership, and community.

I think it'd make sense to reflect the Member Agreement too:
>The mission of the Consortium is to lead the World Wide Web to its full potential by developing common protocols that promote its evolution and ensure
its interoperability.

The idea being that once the vision statement, purpose statement, and values, are in place, work can begin on strategies for realising them.

**Comment by fantasai** [comment]
As  a side-note, the training mentioned that "Purpose" and "Mission" are interchangeable, with the former being more common these days in the regions the training course primarily operates in. I think the text Léonie quotes (the "Mission of W3C") fits in with the Mission/Purpose; the Vision is the world we want to create, so I think that's [this one](https://www.w3.org/TR/w3c-vision/#vision-web).

**Comment by cwilso** [comment]
This does align very much with how the Vision document is structured, with a caveat that we felt it was important to separately capture the vision for the Web and the vision for the Consortium (how it supports the vision for the Web is of course important, and integrated).  The operational principles are very much values by another name (they were labelled values at one point, IIRC).

This is a layered approach:
- Vision for the Web (basic core underlying ideas behind the Web): ["W3C's Vision for the Web"](https://w3c.github.io/AB-public/Vision#vision-web)
- Vision for the W3C/the Consortium as a whole: what role the Consortium plays for the Web, how it functions ["Vision for W3C"](https://w3c.github.io/AB-public/Vision#vision-org).  The much shorter, pithier version of this is the [Mission statement](https://w3c.github.io/AB-public/Vision#mission); I inserted that section because I felt it was important to have the elevator pitch.  
- Operational Principles for W3C/the Consortium: What principles/values we will use to guide us along the way and ensure we are aligned with that vision ["Operational Principles for W3C"](https://w3c.github.io/AB-public/Vision#op-principles)

All of these are relating to/covering the entire Consortium - i.e., the Membership as well as the Corporation.  This is important: **I think we should recognize that W3C is *not* the same as even a typical non-profit, for-the-public-good organization**: we are a Consortium, and the work is done differently here.  The purpose/role of the Team is not 1:1 the purpose/role of everyone in the Consortium; you cannot articulate what the _Members_ will do to achieve the Consortium vision, in the same way you can clearly articulate what actions the Board/Team should perform.  This sounds like an aspect not taken into account in the training; that the Members and the Team participate differently in the Consortium.

With that in mind, I do definitely agree there is a strong need for an additional layer here, which is the "Purpose of W3C Inc" (aka the Team+the Board) and how it works toward/ensures fulfilling this vision; what the directly-funded-and-controlled organization is expected to do.  This is somewhat implied by the section of the Vision of W3C that says "The fundamental function of W3C today is to provide an open forum where diverse voices from around the world and from different organizations and industries work together to evolve the web by building consensus on voluntary global standards for Web technologies." - but it would be better to have what is essentially the "Inc Charter".  Off the cuff, what I mean by "corporation purpose" would be something like:

> The purpose of W3C, Inc is to ensure the Consortium is an open, equitable forum where diverse voices from around the world and from different organizations and industries can work together to evolve the web.  W3C, Inc will ensure the entire Consortium respects and follows the operational principles, and that the technical standards created are aligned with the Vision of the Web.  W3C, Inc is specifically tasked with ensuring global participation and community.

That's not really intended to be a draft, just an attempt to illustrate the qualitative difference.  I'm happy to help wordsmith a purpose, just consult, or leave it to the Board/Team entirely, as desired;  I'm personally okay with this being a separate document, or being inserted into the current Vision document, but I don't think it would be a good idea to create and insert a "corporation purpose" into the current Vision without at least direct involvement from the Board, if not them outright owning it as a separate document.

To sum up, and take a stab at how this compares to the sketch of the training you received: 

- The vision described by the training is the vision for the Web and the Vision for the W3C (the consortium)
- The purpose described by the training is partly the Mission statement in the current doc, but mostly not written (this is the sketch above), because it needs to describe _what the organization will do_; what function the resources under W3C, Inc's control should focus on.  (yes, that is "guiding" the Consortium - but you can't say what the Members are going to do, only give them values and principles they have to follow.)
- The values described by the training are the operational principles; there may be additional principles that are relevant to W3C, Inc (e.g. the Team has operational principles/directives that the Members don't).  This is in the purview of the Team led by the CEO, imo.

I will call out that all the references to vision/mission/purpose may be different for Consortium vs inc: For example, the Member agreement *should* refer directly to the Vision's [Mission statement](https://w3c.github.io/AB-public/Vision#mission), because it's talking about Members of the Consortium.  The Bylaws might not be; the 501(c)(3) filing is definitely talking about the W3C, Inc purpose, not the Consortium as a whole.

_(I do, btw, want to call out an allergy to the phrase "lead the web to its full potential" - without defining full potential, this means nothing; and the purpose statement should define the actions that W3C staff members need to execute on.)_

**Comment by cwilso** [comment]
I will note the Board's draft purpose (currently in PR: https://github.com/w3c/board/pull/166).  I'm unsure if we should:

- Leave "purpose" to that document
- Expand and/or better align/refer to the board's purpose from https://www.w3.org/TR/w3c-vision/#vision-org.
- something else

thoughts?

**Comment by avneeshsingh** [comment]
we started from the structure which is mentioned in the board training.
But, the vision evolved from that stage to current stage over last 5 years. We have two vision statements, mission statement, operating principles. I am concerned that if we keep on adding more statements, it will become confusing for the audience.
Ideally any vision, mission or purpose statement of an international organization should not mention things like "501 C3 organization", because this is more of country specific legal matter. It is ok to have it in article of association, but not in public oriented vision document.

**Comment by cwilso** [comment]
@avneeshsingh I'm not sure if you're saying you'd rather have the Board's purpose need fulfilled by the "W3C vision" section of the vision doc rather than the Board having a separate doc, or you're just saying you don't want to have another section added in the Vision(I agree).

**Comment by dwsinger** [comment]
I do not think that Board will not develop a vision or purpose for the consortium overall or its technical program.  I do think we can refer to the Vision as it is for that. Whether we want or need something called a "purpose" from the AB I am not sure. Personally I think we can cope without it.

**Comment by fantasai** [comment]
I wonder, given the last round of edits, whether it would make sense to rename this section to "Purpose of W3C"? https://www.w3.org/TR/w3c-vision/#vision-org

**Comment by cwilso** [comment]
I think, given the Board is working on a document entitled "W3C's Corporate Purpose" (https://github.com/w3c/board/pull/166) that might be a confusing thing to do.

**Comment by avneeshsingh** [comment]
@cwilso wrote:
 I'm not sure if you're saying you'd rather have the Board's purpose need fulfilled by the "W3C vision" section of the vision doc rather than the Board having a separate doc, or you're just saying you don't want to have another section added in the Vision(I agree)."
Indeed I do note want to add another seciton in vision document.
And it would be good if board's objective of having a purpose statement can be fulfilled by using relevant text from the vision doc so that it looks in-sync with the vision doc to external audience.

**Comment by dwsinger** [comment]
I don't think the Board's purpose helps here. The Board's purpose is for the corporation, and could easily be (it's not done yet) something that basically says "be a corporation that enables the consortium and its members to achieve its vision and pursue its goals". That rather assumes that the consortium has goals it aims to reach.

I agree, however, having multiple documents with the same title would potentially be confusing, even if by reading them you can work out that they apply to different contexts.

**Comment by cwilso** [comment]
@avneeshsingh I would second @dwsinger; I think the draft Purpose statement of the Board is a document making a different point; it does explicitly reference the Vision document as the Consortium's vision, but it is laying out a purpose statement specific to W3C, Inc.  

I think, at this point, that we should resolve this issue as "the Board is working on a Purpose statement, that document references the Vision but is a separate document intentionally, and we should not define the Corporate Purpose in the Vision document.  (At some point in the future when the Board has published their purpose, we could reference it from the Vision perhaps if the Board thought it was important.). What do you think of that plan, @LJWatson @mnot @dwsinger ?

**Comment by avneeshsingh** [comment]
OK, looks good. If it is referring vision document, I think there will be no confusion.

**Comment by mnot** [comment]
Just FYI - it's not out of the question that the board will adopt the purpose statement at its meeting this week.

**Comment by avneeshsingh** [comment]
“I agree, however, having multiple documents with the same title would potentially be confusing, even if by reading them you can work out that they apply to different contexts.”

 

+1, it would be good to figure out little different titles for the documents.

**Comment by LJWatson** [comment]
As the person that prompted the opening of this issue, I think it can be closed now. The Board has drafted it's purpose and that document references the W3C Vision, so I think the dots are joined up enough.
