### ISSUE TITLE
Define the purpose of Vision document

### ISSUE THREAD

**Issue by avneeshsingh** [w3c/AB-public#22]
Every time I come back to this vision and strategy work, the quantity of material in this repository confuses me, what purpose are we trying to solve. I think we have good amount of material, and now we need to make it crisp and concise. For achieving this, it would be good to list what is the purpose of this exercise. I am lisitng some points as a starting point:
1. Clarify the unique purpose of existence of W3C.
2. Provide a compelling and meaningful direction to W3C as an organization and as a community. One should be able to derive long term, mid term and short term goals from the direction.
3. Communicate the purpose and the direction of W3C to external audience in an easy to understand way.
4. Clearly define operational principles for providing a basis for decisions. This may end up in a different document because it should be in more detail. One way can be to have short version in vision and strategy document and detailed version in separate document.

**Comment by dwsinger** [comment]
Actually I started it because I saw a critical need for 3 and hence 2.  I agree that 4 is also important but I strongly agree it needs separate treatment

**Comment by michaelchampion** [comment]
Hmm, how can we communicate the direction to an external audience without getting specific enough about internal principles to guide actions to move in that direction?  There's a risk that the principles become an semi-meaningless slogan, like "lead the web to its full potential" has become in the years since the founders' vision of an open planform essentially as powerful as the proprietary platforms became real 10-15 years or so ago. 

I do accept that turning principles into clear guidelines for action is a lot of work, and probably something we iterate toward over some years. But I still believe a " short version in vision and strategy document" is the highest priority for this exercise, and the external and internal direction statements should be derived from that vision and strategy.

**Comment by dwsinger** [comment]
well, have a look at the first two sections of the [Vision](https://github.com/w3c/AB-public/tree/main/Vision) . They are about the web and its meaning to the world. They are outward looking.

The second two sections are about the consortium and our values in how we operate. They are inward looking.

Both are valuable.

**Comment by rigow** [comment]
Which raises the question whether the web of data is still part of that vision. I also would like to point out that W3C is not operating in a total vacuum because it is also embedded since its inception in its regional regulatory and political environment. The ease of that integration was partly due to W3C's academic fundaments and renown. 
In the current crisis there is so much in flux that it is hard to see how past and future vision are coming together. This is why I would like to see a careful steering.

**Comment by cwilso** [comment]
I don't think Avneesh's points were in exact reverse order.  I do think the purpose of the vision document should be summed up as:

- Briefly describe how we see the vision of the Web itself, and how it supports humanity (to an external audience).  This should link to the TAG's EWP.
- Communicate the purpose and role of the W3C (to an external audience).
- Clearly define the principles and values that should underlie our operations. (This is for an external and Membership audience, as it is what should guide our operations.)
- Develop operational principles to ensure the organization's work reflects our values and principles, as we execute our purpose. This may end up in a different document because it should be in more detail; this is where, for example, we will explicitly link principles to horizontal reviews, etc.

**Comment by chaals** [comment]
I agree this issue seems to be the same as #53

**Comment by frivoal** [comment]
[Elsewhere](https://florian.rivoal.net/ab/2023/vision-charter/), I had written:

> The scope […] is articulation of the W3C’s mission, values, purpose, and principles; in other words, our vision for W3C as an organization in the context of our vision for the Web itself. The goal of this vision is not to predict the future, but to have shared principles to guide our decisions as we go. 

> The following topics are out of scope[…]:
> […]
> * An operational strategy for W3C Inc. as an organization: such a strategy should take the Vision into account, but it isn’t the Vision itself.
> * Recommendations for or against specific technologies: technologies are not value neutral, and preference for or against a particular technologies should be influenced by values as articulated in the Vision, but the Vision should support thinking about such things, rather than contain specific answers.

> This Task Force will have succeeded if it develops a document that:
>
> * Helps the world understand who we are, what we do, and why it matters.
> * Is opinionated enough to provide a helpful framework when making decisions, particularly on controversial issues.
> * Is grounded enough in the shared values of the W3C community that it represents the emergent consensus of most of our participants.
> * Is timeless enough that it doesn't need frequent revision. 
> 
> Examples of such documents would be the original [Mozilla Manifesto](https://www.mozilla.org/en-US/about/manifesto/details/), the [Debian Foundation Documents](https://www.debian.org/doc/manuals/debian-handbook/sect.foundation-documents.en.html), and the Médecins Sans Frontières (MSF) [Charter](https://www.msf.org/msf-charter) and [Chantilly Principles](https://www.msf.org/sites/default/files/Principles%20Chantilly%20EN.pdf).

Thought the phrasing is different, I see that as compatible and essentially the same as what @cwilso said above.

**Comment by swickr** [comment]
Nicely expressed, @frivoal ; I suggest we (add and) put this in a Status of This Document in the Vision document itself.

**Comment by cwilso** [comment]
Resolved by TF, take @frivoal 's text above and add in preface section.
