### ISSUE TITLE
Improve Vision language to avoid colloquial or complex expressions

### ISSUE THREAD

**Issue by dennis-dingwei** [w3c/AB-public#23]
In my reading the current version of the Vision under drafting , some of the sentences are colloquial, and would like suggest it could be more in literary languages. 

(1) 1st paragraph: "**It has become much more than that**;"
Suggest change to: "It has evolved as a fundamental part of the lives of much of humanity, ..."

(2) 2nd paragraph: "The Web is a force for good; **indeed,** it has catalyzed major social changes."
Suggest change to: "The Web is a force for good, and it has catalyzed major social changes **substantially**."

**Comment by michaelchampion** [comment]
I may have written those sentences long ago (sounds like my writing style), and agree with the critique that they don't havet the right tone for this document.  @dennis-dingwei's suggested changes are reasonable.  I believe "has substantially catalyzed major social changes" sounds a bit better, but this is a subtle point of English grammar https://www.grammar.com/2-where-do-adverbs-go and either is OK.

**Comment by dennis-dingwei** [comment]
Agree to move **substantially** ahead, as it is reasonal to be highligted... @michaelchampion

**Comment by TzviyaSiegman** [comment]
Some advice from an accessibility course Wiley is developing with TetraLogical (thanks @LJWatson)

1. Use short sentences where possible. To do this:

- Split long sentences into two
- Aim for a maximum of 20 words per sentence
- Add in some 3 to 4 word sentences
- Remove redundant words e.g. during instead of during the course of and write instead of write down
- Avoid adverbs e.g. fairly, quite, usually

2.  Aim for words of 1 to 2 syllables. Anything over 3 gets harder to read.

3. Avoid using abbreviations and acronyms when possible.

4. Use person-first language - A disability is what someone has, not what someone is. When writing about people with disabilities, avoid referring to them as "the disabled". You can use "disabled people" or "people with disabilities" instead.
Avoid negative language - When writing about disability, avoid words or phrases that reflect prejudiced, stereotyped, or discriminatory views of particular people or groups. For example:
- Suffers from Cerebral Palsy"
- "Confined to a wheelchair"
- "Mentally/physically challenged"

Instead, use neutral language such as:
- "Has Cerebral Palsy"
- "Wheelchair user"
- "Has a mental health issue"

5. Avoid ableist language - Avoid describing people with a disability as super-humans, differently-abled, or heroes. Equally, do not refer to people without a disability as "normal". Use "disabled" and "non-disabled" instead.

**Comment by cwilso** [comment]
Partial fix pending.

**Comment by chaals** [comment]
I think this is a permanent issue for everything we write. Many thanks to @dennis-dingwei for raising it.

I propose that because this is a recurrent issue, we create a label for "clearer language" or something in any repo we have, and then we ask people to raise specific issues or PRs about specific bits of language they find unclear, and add the label, and when it's documented how to do that we close this issue.

(This is something that applies across the W3C - and to almost all of my work outside W3C too. So we should see if we can generalise the proposed solution, or if someone else already has a good model we can copy).

**Comment by chaals** [comment]
See also #23 ...

**Comment by cwilso** [comment]
First round (intro) is done; need to do the same review of the rest of the principles.

**Comment by cwilso** [comment]
After reviewing, I think subsequent work has fixed this in the rest of the principles.  @dennis-dingwei, could you do a review and call out any text that seems complex or inaccessible?

**Comment by dennis-dingwei** [comment]
Yes, thanks.
