### ISSUE TITLE
How should we develop the "W3C Vision and Values"?

### ISSUE THREAD

**Issue by chaals** [w3c/AB-public#57]
Some of the discussion in #53 seems to revolve around the question of how a document outlining W3C's vision comes into being and is accepted by the community.

There have been people in the AB working on a document that aims to act as a basis for the work, and there are suggestions that this is the wrong model, and the full Working Group model should be used for this work.

There are other possible approaches (incubate it in WICG, appoint a new Director, ask the Board/Comms Team/next-door neighbours to do it...).

How do we pick the right one, and what are the criteria?

**Comment by fantasai** [comment]
My proposal is that we manage it like other major AB-managed documents such as the Process, and put it on the W3C Statement track by publishing it as a Draft Note.

**Comment by chaals** [comment]
Does "like other major AB-managed documents such as the Process" that mean with a Community Group where it is managed?

I think it makes little sense for discussions to be held in AB-only space, less for decisions to be taken based on such discussions, and none at all to claim that such decisions are not reasonable questions to re-open in a member-visible discussion.  

I equally think that it makes a lot of sense for discussions to be member-confidential. There are concrete things I think are important, that will only get frank answers if they are not considered fair game for republishing. Likewise, I think it's important to enable in-person discussion (whether on a teleconference or at e.g. an AC meeting) on the substance of the document.

I don't mind having the "current state" of the document publicly visible, and think it is important to make at least "Working Drafts" visible to the public and actively solicit review. But I don't think it is critical that document drafts are all public. IMHO there are *potential* downsides to such an approach depending on how it is implemented.

**Comment by frivoal** [comment]
> Does "like other major AB-managed documents such as the Process" that mean with a Community Group where it is managed?

Kinda. We should have a chair, a mailing list, a repo, an issue tracker, a meeting schedule, agendas… Setting up a CG is not necessary to get that, but it's just a couple of buttons to click to get the the infrastructure in place, which is convenient.

However, I suspect we might want to roll these out manually, and to not to call it a CG, for two reasons:
* CG typically don't necessarily need to abide by the Process, and that's not what we want to express here: developing a Statement is very much governed by the Process, and an AB Note is bound to it. A CG acting under delegation from the AB would have to follow that too (or it wouldn't work), but the name CG doesn't make that obvious. Calling it a task-force of the AB probably makes that clearer. In theory, the same would be true of the ProcessCG, but the Process is old and has legitimacy on its own, with Statements are new, and we may not want to give the wrong impression, by having people think "oh, it's just a CG, that has no standing".
* CGs are open to everyone, and we may not necessarily want that here. I do think we should do all our work in public. Per the Process, we do have to formally respond to any issue filed by anyone. But maybe we want to limit the "we" who does the responding to actual W3C Members and IEs, as that may help avoid loosing focus or diluting opinions too much.

My suggestion would be:
* publish it as an AB Note, with the intent to make it a Statement eventually
* set up a group under delegation from the AB, similarly to the process, but call it something like the "Vision Task Force"
* Participation in task-force is open to all W3C members & IEs (and expected from AB members)
* Have an explicit chair, an explicit editor, periodic meetings with an explicitly triaged agenda, have a defined work-mode either with synchronous decision making in calls or async CFCs, but either way document what it is.
* do all the work in public
* take in and respond to issues from anybody (as required by the Process)
* Solicit horizontal and wide review, and do work on it as per the Process's expectation
* As long as we're at Note stage (and not yet bound by consortium-wide consensus), if the TF fails to get to consensus on some things, the AB makes the call. This is so that we can make progress and avoid problems of consensus by attrition/exhaustion. In order to publish it as an actual Statement, it will still need to go through AC Review, so this is not a license to ignore everybody's opinions, and the AB/TF would still have to write a document that's compelling if it doesn't want to be stuck in FOs later.

If that sounds plausible, or at least intriguing, I am willing to give a shot at writing the charter for such a Task Force.

**Comment by chrisn** [comment]
> If that sounds plausible, or at least intriguing, I am willing to give a shot at writing the charter for such a Task Force.

It does, although what you describe sounds a lot like setting up a WG, minus the AC charter review. But I'm OK either way, a WG or a TF that operates as you describe.

**Comment by avneeshsingh** [comment]
Now board of directors are the highest authority in W3C. The vision and corporate strategy of an organization is owned by the BOD. BOD may or may not work on it, but they need to formally approve it and need to be committed to it.

So, what should be the relationship of BOD with this document in our case?

**Comment by LJWatson** [comment]
>So, what should be the relationship of BOD with this document in our case?

The Board discussed this when we met during the W/C 13 Feb. As @dwsinger noted in his [brief informal report to the AC](https://lists.w3.org/Archives/Member/w3c-ac-forum/2023JanMar/0097.html):

>the AB-curated community vision is a key element and the Board reaffirmed its support for the continued development of this, in community, led by the AB.

**Comment by frivoal** [comment]
> If that sounds plausible, or at least intriguing, I am willing to give a shot at writing the charter for such a Task Force.

Here we go: https://lists.w3.org/Archives/Public/www-archive/2023Mar/att-0000/index.html

I make no claim that this represents the position of anyone: this is just my input into this debate. It is to a large degree inspired by the de-facto unwritten charter of the Process CG.

I could be entirely wrong, but given the general level of angst, I believe something explicit like this would be useful. It would keep the AB in the leading position just reaffirmed by the Board, while providing much a clearer framework for everybody who wants to participate.

**Comment by dwsinger** [comment]
I think that this goes in the right direction, and perhaps it's the best as it creates real identity for the group, but I worry that it seems rather heavyweight. 

We should enable similar review and engagement opportunity for the TAG docs and there are at least 3 of those (Ethical web, web platform design, and privacy), and either we'll be tempted to do them all in one group (thus diluting the focus and engaging people with different interests) or we'll end up spinning up many per-document groups.

In other bodies, it's easy to spin up a lightweight group with a mailing list and so on, for ad-hoc purposes. Even an Interest Group takes a charter and AC review at the W3C, though. A CG per document seems wrong too, as that's open to the outside, and that seems odd for documents that 'clarify our identity'.

**Comment by fantasai** [comment]
> In other bodies, it's easy to spin up a lightweight group with a mailing list and so on, for ad-hoc purposes.

That's basically what @frivoal is suggesting, from what I can tell (he's using the term Task Force), except that it's also got a charter--which I think we do need here, because it clarifies the scope and the authority of the group. There's been a lot of debate and confusion over these, so I think writing them down is important.

**Comment by dwsinger** [comment]
The minor snag is that we don't have any definition of what a w3c task force is in general. the write-up seems fine, however.

**Comment by frivoal** [comment]
> The minor snag is that we don't have any definition of what a w3c task force is in general. the write-up seems fine, however.

I take it to be a vague generic term for groups that aren't predefined in general, and for which we therefore need to provide a specific definition if we want to set one up, which this charter attempts to do.
