### ISSUE TITLE
Extract useful points from AB discussion

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#6]
originally filed at https://github.com/WebStandardsFuture/Vision/issues/35.

**Comment by tantek** [comment]
This is another “to-do list” issue that is open-ended and requires someone to go through a bunch of somewhat lengthy existing discussions elsewhere to try to extract specific proposals for improvement, similar in that regards to [https://github.com/w3c/AB-public/issues/2](https://github.com/w3c/AB-public/issues/2) except that was primarily about extracting from a curated pre-existing crafted text, and this issue is more of an amalgam of a bunch of lists of things from several authors, some of which are already handled in the Vision.

Similar to [https://github.com/w3c/AB-public/issues/2](https://github.com/w3c/AB-public/issues/2):

Proposed resolution:
* defer this issue and leave it open to specific proposals (in new issues) for inclusion of any relevant specific points &amp; content from the those old discussions. If there are no specific proposals by end of year 2022, close this issue without changes, noting that new issues for specific points may still be raised, yet due to lack of interest, no one is being assigned to attempt to extract specific points from other people’s lists made in GitHub comments. I.e. if folks feel strongly about specific points in their lists, it is their responsibility to file new specific issues for each point they feel strongly about.

(Originally published at: https://tantek.com/2022/227/t9/)
