### ISSUE TITLE
W3C is a Voluntary standards forum

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#69]
As per #61 : 

@frivoal and @tantek suggested that we should be explicit that W3C is a voluntary standards forum, as opposed to legislated or otherwise compelled standards. We may want to expand on this further later to summarize what voluntary means for those who are not familiar, but we should explicitly state what is already true, and set expectations accordingly.

**Comment by dwsinger** [comment]
True (mostly, though some are adopted by governments), but why does this belong in the Vision? We don't try to explain _who_ we are in the Vision, do we?

**Comment by frivoal** [comment]
The single word PR doesn't get into all of that, but I think this voluntary nature is important to understand W3C and how/why it does things. I think a lot follows from that.
* No part of our vision is to force any particular party to do any specific good thing we'd like to see happen, not because there are no good things we'd like to see happen, but because we're not in the business of forcing anyone to do anything.
* That we work by consensus is inherently tied to being a voluntary body, and the value of what we produce is carried by the fact that it does represent broad consensus.
* While nobody can force anyone to do anything, anybody (regardless of affiliation or market power) can raise issues or make proposals, and through persuasion (rather than vote counts), move the needle.
 
And, for instance, I'd say the following widely shared views derive, at least in part, from the fact that we're a voluntary body:
* Proposing or expecting, in the course of W3C's activities, to try and compel some implementer to ship / not ship something against their will is a non starter. Influence, yes, compel no. Someone might have legitimate reasons why they think someone else should be forbidden from or compelled to doing certain things, but W3C is not the right forum to try and achieve that. Charter proposals, Process proposals, Formal Objections, etc, in that direction won't work, and shouldn't be expected to.
* Proposing to limit the number of attendees by large companies would be counter productive: they don't get more of a say over what anyone else does by having 1 or 100 reps. On the other hand, a company large enough to send 100 reps is large enough to be involved in a lot of things, and we need all the stakeholders around the table if the attempts at consensus are to be representative of all parties involved in the things being discussed, and to have an opportunity to shift eachothers views.
* Proposals that go in the direction of "following the rules is all you should need to get a REC, consensus on the substance beyond the WG is not necessary" would not not strengthen the ability of a focused group of experts to tell the word what to do, and instead would weaken the standing of RECs, by shrinking the set of people whose consensus uphold the Recommendation.
* A principle underlying the patent policy is that although it encourages and structures the members' licensing of relevant patents, it doesn't force anyone's hand. Members have to first opt into the group, and they always have an opportunity (no matter how unpleasant that might be) to opt out of licensing any particular claim.

I think this notion and the various things that derive from it have guided quite a few structural approaches we have, and proposals that would ignore that would go against the grain. So we should be upfront about that.
