### ISSUE TITLE
Add 'industries into 3rd bullet of principles?

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#7]
originally filed at https://github.com/WebStandardsFuture/Vision/issues/33.

**Comment by cwilso** [comment]
Industries has been added into the principles.

**Comment by igarashi50** [comment]
> Implement a unified, extensible, Web architecture, which continues to address evolving use cases for the general public.

I think that we should also add "industries" to the above bullet of principles since Web technologies are used in industries, such as publishing, automotive, broadcasting, IoT, etc.  In some cases, they are not connected to the public Internet. The following is my suggested text.

_Implement a unified, extensible, Web architecture, which continues to address evolving use cases for the general public and industries._
