### ISSUE TITLE
Resolve issues associated with antitrust before progressing further

### ISSUE THREAD

**Issue by jwrosewell** [w3c/AB-public#80]
There are several parallel issues associated with the [W3C Antitrust Guidelines](https://www.w3.org/Consortium/Legal/2017/antitrust-guidance) including enforcing them and modifying them that are currently progressing in other groups.

- [Antitrust policy](https://github.com/w3c/board/issues/26)
- [Upgrade antitrust provisions](https://github.com/w3c/AB-memberonly/issues/88)

These should be resolved before progressing the Vision further.

The document asserts that there are unintended consequences that harm society.

This is true of any technology since the dawn of time. Taking one example.

> The ease of gathering personal information has led to business models that mine and sell detailed user data, without people's awareness or consent. 

This is primarily a matter for data controllers, processors, and law makers. The presence of this language could be seem to provide legitimacy to attempts to interfere with lawful interoperability. However with care it could be modified to emphasis transparency of processing, use, and consent rather than interference.

Taking another.

> Rapid global information sharing has allowed misinformation to flourish and be exploited for political or commercial gain.

This has been the case since the invention of communication. The language could be modified towards a vision which guides interactions with the web information to be verifiable and traceable based on individual users preferences.

However, If we list one unintended consequences why not list them all? Do we add language concerning winner take all business models that concentrate control over access and interoperability in practice into the hands of a small number of trillion USD+ market cap for profit companies?

These complex issues in the current draft will be easier to settle once the issues associated with antitrust have been resolved. Upgraded guidance and active enforcement will inform the language and scope of the Vision.

**Comment by TzviyaSiegman** [comment]
@koalie the MO of this task force is for issues to be raised and PRs to be assigned to specific people after discussion (either in GitHub or in meetings). It was getting unmanagable with multiple PRs and merge conflicts.

**Comment by chaals** [comment]
The text seems to have changed significantly since this issue was raised.

I'm not sure if we need to deal with anti-trust guidance before we work on this, and I note the Board of Directors has a proposal to do so in any event. If the purpose of this issue is to stop work until that is finished, I oppose doing so. We can work on more than one things at a time, and anyway this work is slow in nature - possibly more so even than updating the antitrust guidance.

However, I think it is important that we talk more in depth about how we envision the competitive landscape we want the web to support and enable. Should that be a seperate issue, or does this one cover it?

**Comment by cwilso** [comment]
The Board of Directors has issued draft updated guidance on anti-trust (https://lists.w3.org/Archives/Member/w3c-ac-forum/2023OctDec/0115.html).  I believe this issue can be closed.

**Comment by jwrosewell** [comment]
This issue must not be closed until the Antitrust and Competition Policy has actually been updated and the relationship with the Bylaws and related documents established. Only then can the impact to other subordinate documents and work be progressed.

At the time of commenting only the 2017 guidance exists at a [URL that lacks version control](https://www.w3.org/policies/antitrust/).

A screens shot of that page follows for the record.

![image](https://github.com/w3c/AB-public/assets/1679482/c1181a48-719c-4499-8fd9-dd7a865458da)

**Comment by jwrosewell** [comment]
@chaals 

> However, I think it is important that we talk more in depth about how we envision the competitive landscape we want the web to support and enable.

The Antitrust and Competition Policy that the Board put in place, and which I sincerely hope complies with applicable laws if it is to support the filing made to the DoJ by W3C, will define the limits of any such discussion. Significantly it is not for a neutral technical standards body to envision a competitive landscape to be supported and enabled. That is the role of the market supported by regulation where necessary.

**Comment by cwilso** [comment]
The Board's new Antitrust guidance was sent to the entire Membership for review over a month ago.  I will leave this issue open for the AB chairs as a general concern about antitrust guidance, but I should be clear we are not pausing work on the Vision at this time.  We have not discussed, and do not plan to discuss competitive landscape in the course of developing the Vision; if that is for some reason needed, we will do so after the new antitrust policy is approved by the Board, and after consulting with the Board.

If you have a disagreement with this course of action, please take it up with the Board.

**Comment by chaals** [comment]
@jwrosewell:

> Significantly it is not for a neutral technical standards body to envision a competitive landscape to be supported and enabled. That is the role of the market supported by regulation where necessary.

I believe we agree that we are bound by regulation affecting marketplaces and we should operate in real marketplaces as they are rather than beginning by assuming something we would like to be true.

However, it is appropriate for our discussions to envision different marketplaces (this is not the same as illegal activity such as price-fixing or working to create illegally distorted marketplaces), and for those discussions to inform regulators.

It is also sometimes the case that within the rules placed by regulators there are different choices we can make. 

Currently we often seem to pretend that there is one homogenous market of users, with one homogenous set of wants, which allows us to claim we center everything on the needs of users, modulated by the possiblities offered by vendors.

That seems preposterous - there are many users, and they are a highly diverse set with different and in many cases conflicting goals and desires. But the consequence of not accepting such a proposition is that we are required to think about what these different options mean, and how we should respond to them. That applies both in terms of considering whether the current limits set by regulators are something we might recommend changing, and considering more specific questions where the options are all apparently well within the bounds set by current regulators and feasible for real markets to adopt.

**Comment by cwilso** [comment]
I will note that the Board has formally adopted the new Antitrust guidance: https://github.com/w3c/board/issues/26#event-12036845174.

**Comment by jwrosewell** [comment]
I wouldn't be able to determine if the issues associated with antitrust have been resolved as the link is not accessible.

I can however check the [W3C web site](https://www.w3.org/policies/antitrust/) and observe that the version from March 2017 continues to be the version displayed.

![image](https://github.com/w3c/AB-public/assets/1679482/fac0d192-6953-47bc-9801-7426dc1b35c4)

If there is an updated version it would be helpful to assess it to determine if the Board have addressed the issues. The version I saw in draft privately did not address the issues.

**Comment by koalie** [comment]
This is on my TODO today to deploy on the site, and announce.

**Comment by koalie** [comment]
> I will note that the Board has formally adopted the new Antitrust guidance: [w3c/board#26 (comment)](https://github.com/w3c/board/issues/26#event-12036845174).

The 2024 version is now available on the W3C website: https://www.w3.org/policies/antitrust-2024/

**Comment by cwilso** [comment]
AB examined and resolved to close in meeting on April 11 2024.

**Comment by jwrosewell** [comment]
@cwilso have the AB completed the antitrust compliance training the Board agreed to implement? If so please can you share the material so other members of the W3C eco-system may benefit from this.

**Comment by frivoal** [comment]
@jwrosewell I am not sure where you have seen that the board agreed to implement compliance training for the AB. Can you give a source for this?

**Comment by jwrosewell** [comment]
@frivoal In this [notification](https://lists.w3.org/Archives/Member/w3c-ac-forum/2024JanMar/0129.html).

I assume by your question that the AB have not received such training and therefore @cwilso needs to re-open this issue so that it can be returned to once the AB have received the compliance programme training, can amend the Vision to comply with antitrust, and then clearly explain how the Vision complies with antitrust to the members and wider web community.

**Comment by frivoal** [comment]
The message you refer to does not say that the board has agreed to implement compliance training for the AB. Did you mean some other message?

**Comment by cwilso** [comment]
I will note that I closed this issue in a secretarial capacity during a meeting with the entire AB present; there was consensus from the entire AB to close it, and thus I will not be re-opening it.

**Comment by jwrosewell** [comment]
@frivoal The message I referred to advises that a compliance programme will be implemented. That is very welcome. I believe that the CEO and Board will ensure that this compliance programme will include compliance training for all W3C participants. If they or you believe otherwise perhaps they could respond here.

@cwilso I Formally Object to the decision of the AB to close an issue related to antitrust where the AB knew that a compliance programme was being developed and had yet to benefit from that compliance programme and training. The remedy would be to re-open the issue and revisit once the compliance programme is implemented and training received. At this point the AB can advise exactly how they consider the Vision complies with antitrust.

**Comment by cwilso** [comment]
I refer to the [Process](https://www.w3.org/2023/Process-20231103/#registering-objections) : Formal objections are filed with the Team, not announced to participants in a Github issue.  The Team Contact for the Advisory Board may be found on the Advisory Board page (https://www.w3.org/2002/ab/).

**Comment by frivoal** [comment]
> The message I referred to advises that a compliance programme will be implemented. That is very welcome.

It does say that the Board has instructed the CEO to develop and implement a compliance program. That is indeed welcome.

> I believe that the CEO and Board will ensure that this compliance programme will include compliance training for all W3C participants.

If you can provide any source for that belief, that would be great. I am not saying that this necessarily will not be the case, I just do not know. But earlier you have specifically asserted that the board had agreed to implement compliance training for the AB. If you have a source for this, please share it, as I would be interested in learning more. If this is speculation, please say so as well.

**Comment by frivoal** [comment]
Closing this issue simply represents the fact that the AB does not think that there is anything actionable here, nothing less, nothing more. Should new relevant facts become available (through training or otherwise) we can certainly open more specific issues, or reopen this one if it turns out to be relevant somehow.

**Comment by jwrosewell** [comment]
> If you can provide any source for that belief, that would be great.

@frivoal All compliance programmes include training. Please speak with Lee Gesmer.

> AB does not think that there is anything actionable here

@frivoal That is disappointing and shows that the revised Antitrust and competition policy (2024) has not been understood highlighting the need for AB training. I also note it is disappointing that the policy lacks specificity to aid understanding and contains contradictions which will need to be address in the compliance programme and training.

I'm grateful that this thread has highlighted that the compliance programme is neither in place or training received. As such AB members, and other members of a Council (assuming one accepts that the Bylaws as amended in 2023 are the operative Bylaws which they are not) do not have the prerequisite knowledge to participate in the resolution of Formal Objections related to antitrust including the Formal Objection generated as a result of this thread. The sooner the compliance programme and training is in place the better.

**Comment by frivoal** [comment]
You made a specific assertion about what the board had supposedly agreed to implement compliance training for the AB, but it turns out that what the board has done is task the CEO to develop and implement a compliance program. These may be related, but they're not the same.

You now claim, as a statement of fact, that the Bylaws as amended in 2023 are not the operative Bylaws. Do you have a source for that?

**Comment by jwrosewell** [comment]
@frivoal a robust compliance programme will include training. I believe that W3C are now starting to consider antitrust seriously and thus the compliance programme will be a robust one. Do you believe otherwise? In the interests of brevity I used a single short sentence to convey the situation and logical outcome. When communicating with you in the future I shall endeavor to layout all the steps in detail.

In relation to your question concerning the Bylaws. This was covered in great detail within the Advisory Committee (AC) and is available in the [AC mailing list](https://www.w3.org/Search/Mail/Member/advanced_search?keywords=&hdr-1-name=subject&hdr-1-query=51Degrees+Appeal+re+W3C+Process&hdr-2-name=from&hdr-2-query=&hdr-3-name=message-id&hdr-3-query=&period_month=&period_year=2023&index-grp=Member__FULL&index-type=t&type-index=w3c-ac-forum&resultsperpage=20&sortby=date).

**Comment by frivoal** [comment]
> a robust compliance programme will include […]

I am not debating the content of a compliance program, robust or otherwise. You asserted that the board had done a specific thing, and failed to provide evidence for that, since they had not done the specific thing you talked about. The source provided points to the Board delegating a responsibility to the CEO, which is the opposite of the board deciding themselves how to do it.

> In relation to your question concerning the Bylaws. This was covered in great detail within the Advisory Committee (AC) and is available in the [AC mailing list](https://www.w3.org/Search/Mail/Member/advanced_search?keywords=&hdr-1-name=subject&hdr-1-query=51Degrees+Appeal+re+W3C+Process&hdr-2-name=from&hdr-2-query=&hdr-3-name=message-id&hdr-3-query=&period_month=&period_year=2023&index-grp=Member__FULL&index-type=t&type-index=w3c-ac-forum&resultsperpage=20&sortby=date).

In that thread, you questioned the validity of the Process, not of the bylaws, so that's not what you said above. Also, I seem to recall that the outcome of that discussion is not favorable to the theory you are advancing here.

**Comment by wareid** [comment]
This discussion has steered away from the issue described, and your formal objection has been received, so I believe we can leave things there. The formal objection has been recorded with the Team so they will keep it on record. 

This issue will not be reopened, as the AB has resolved based on the recommendation of those working on the Vision, and the further comments in this thread do not appear to be related to our work on the Vision. The AB does not govern the antitrust policy or the bylaws, that is in the purview of the Board of Directors. We do manage the Process, and any objections related to that have already been resolved (see: https://lists.w3.org/Archives/Member/w3c-ac-members/2023OctDec/0024.html). I recommend you take any questions or concerns you may have regarding antitrust or bylaws to the appropriate body.
