### ISSUE TITLE
Vision for the W3C

### ISSUE THREAD

**Issue by KotisK** [w3c/AB-public#85]
I propose adding the following item in the Vision list:

- 	W3C leads the Web forward, towards the future Web, the semantic Web, the Web of data, the Web of everything (humans, machines, things, processes, services and linked data).

My proposal is based on what is already written in W3C mission web page (https://www.w3.org/Consortium/mission) for "...W3C's vision of One Web" and the "Web of Everything". Also, based on what is written in the Semantic Web web page (https://www.w3.org/standards/semanticweb/) i.e. "The term “Semantic Web” refers to W3C’s vision of the Web of linked data.

Thank you!

**Comment by michaelchampion** [comment]
"Vision of One Web" seems sufficient for vision / guiding principles.  The semantic web, web of things, linked data, etc. are not-universally-accepted details of how one might implement the vision. And to be frank, previous efforts to constrain implementations to conform existing standards have been divisive and counterproductive.  (The sad saga of XHTML and HTML5 https://thehistoryoftheweb.com/when-standards-divide/ being the most painful)

**Comment by michaelchampion** [comment]
> we believe the Web is in part a web of data

The distinction between "text" and "data" is pretty fuzzy.  The early web pioneers seemed to think it was a more important distinction than it has turned out to be.  For example search engines using broad statistical analysis of text and hyperlink patterns turned out to be massively more powerful than those that looked at a page's metadata.  And of course LLMs that have no actual semantic "understanding" of content can use it to do all sorts of things few anticipated 10 years ago, much less 30 years ago. 

Again One Web captures the larger principle here without favoring specific technical approaches.

**Comment by dwsinger** [comment]
I am unsure what specific change is requested, or why what is already said is incomplete or wrong. The vision doesn't characterize the web as being specifically text, data, things, or ideas; it just talks about the web. I think details of technical approaches are out of place in the vision per se. (Though I wish we had a better technical vision, as an organization).

**Comment by mnot** [comment]
-1 on this -- if we're going to try to define what the Web is, we should do so as an explicit effort. This seems like a shortcut to grant some things special status.
