### ISSUE TITLE
Laws then consensus

### ISSUE THREAD

**Issue by jwrosewell** [w3c/AB-public#98]
At the beginning of the 22nd June 2023 meeting @TzviyaSiegman explained how consensus works. Specifically that the work on the Vision does not require unanimous agreement to be advanced.

@TzviyaSiegman did not explain the guidelines that apply to the W3C, which are mandatory and no consensus is required, and how they apply to the work of the Vision Taskforce.

Please can we start the next meeting with this clarification? I have attached the relevant guidelines from EU, US, and UK? There may be other jurisdictions that others would wish to include.

[EU Commission Horizontal Guidelines.pdf](https://github.com/w3c/AB-public/files/11924527/EU.Commission.Horizontal.Guidelines.pdf)
[ftcdojguidelines-2.pdf](https://github.com/w3c/AB-public/files/11924528/ftcdojguidelines-2.pdf)
[UK DRAFT Guidelines.pdf](https://github.com/w3c/AB-public/files/11924529/UK.DRAFT.Guidelines.pdf)

**Comment by mnot** [comment]
James, the documents you've cited are not 'mandatory' -- each is a form of guideline (as you point out), one of them only a draft. Effectively, they are well-stated summaries of the opinions of the regulators at the time of writing. The two operative ones are over a decade old, and thus don't incorporate case law and other developments since.

Attempting to embed the legal requirements in every relevant jurisdiction into global Web standards is a fool's errand. No one (including the regulators) is asking for that to be done -- except for you, seemingly. 

If you have specific items from these documents that you believe apply to the W3C's operation, by all means bring them up in the appropriate place (I'm very much struggling to see how what you reference is relevant to how consensus is defined). Attaching 314 pages of general guidance isn't actionable.

**Comment by jwrosewell** [comment]
@mnot We both understand the importance of the law. You seriously enhanced your knowledge by [completing a degree](https://www.mnot.net/blog/2023/01/05/law-school). Congratulations. 

I surrounded myself with lawyers and economists. See [Movement for an Open Web](https://movementforanopenweb.com/mows-mission-opening-the-web-for-everyone/).

Neither of us is uninformed.

These documents are highly relevant to consensus and are guidance that we need a good reason not to follow if we are to stay "safe". In practice they are mandatory and we need to justify our position.

We can not agree not to follow the law. That would be consensus but would exclude those that wished to follow the law. I'm pointing out that consensus has limits and is not absolute. This is different to the position @TzviyaSiegman used at the start of the last meeting.

In relation to the document being "actionable". I've observed this is an often used line by someone in technical standards trying to dismiss the position of the other person. Work is needed by multiple people to understand and embed these guidelines into the organisation. It is not a simple PR or paragraph. However the documents and input are actionable. What you really mean is there is no willingness to do so.

@TzviyaSiegman we should start the next meeting by clarifying this.

**Comment by michaelchampion** [comment]
@jwrosewell You have not responded to Mark’s challenge to state specifically what in those hundreds of pages of documents applies to the question of what consensus means in the Vision task force. Or any hint of what you suggest Tzvia should actually clarify at the start of meetings.

**Comment by mnot** [comment]
@jwrosewell neither my academic qualifications nor the staffing of your lobbying organsation are relevant to the operation of the W3C. I believe this issue can be closed as off-topic.

**Comment by chaals** [comment]
I don't know that the issue needs to be closed. But unless someone has an actionable proposal, whether that's

"please read a few hundred pages of legal text to work out what we should do, **and then** we can discuss _a proposal_", or

"Let's require that everyone swears fealty to the crown of Belgium at the start of every meeting",

or even something practical and useful, I don't see that there is anything to do with the issue as it stands.

I reject the implication that anyone claims we should do something other than follow relevant laws as sufficiently baseless that it doesn't bear discussion. If someone **does** claim we should do something else, they can raise an issue...

**Comment by jwrosewell** [comment]
At the beginning of the meeting on 22nd June 2023 time was taken to explain how consensus works. As I understand that explanation if there's a minority who do not support a position then the majority can overrule and the Vision moves forward. Correct?

If that is the case then I wish to confirm at the next meeting there can be an exemption when the minority are raising points related to laws. The guidelines documents will be important reference material to support those arguments. Not everyone has to have read them at this stage.

**Comment by mnot** [comment]
Laws are not extraterritorial, generally, and the W3C is not a national standards body.

For example, let's say that Vietnam (to pick a random country) passes a law that disallows use of XML (to pick a random technology). That does not mean that the W3C can no longer publish XML-based formats; it means that those formats can't be used in Vietnam, and (depending on the law's specifics) Vietnamese engineers might have some difficulty participating in the W3C process.

Of course, it may be that participants in the decision _want_ their work product to be usable in Vietnam, and so they argue against using XML. Whether or not that happens is up to the group and process -- in other words, even when there are legal implications, it is **still** a consensus decision.

And since one of the most foolish things one can do is to trust legal counsel that doesn't represent your interests, bringing up those legal points in the group doesn't really help; at most, something like 'just so people know, there are legal aspects to this that you might want to consider' might be appropriate. There is no trump card that lets you automatically win an argument just because you interpret the law a particular way.

Of course, as a Deleware non-profit, US law does apply to the W3C. There's plenty of material from eg the DoJ encouraging standard organisations like ours to use consensus processes. However, to the best of my knowledge there is no legislation, case law, or regulation there that has the effect of requiring a consensus-driven standards organisation to priviledge (pseudo-)legal claims from participants in its deliberations. If you can point me to where I've missed, that I'd be grateful.

**Comment by dwsinger** [comment]
We don't say that we comply with laws as a matter of policy, because the antithesis could not be true: of course we and our members comply, and are expected to comply, with applicable laws. It's not a choice we need to enshrine in policy, because it's not a choice at all. But as Mark points out, what laws apply varies by jurisdiction.

**Comment by chaals** [comment]
It seems @jwrosewell wants to have the group agree that if someone makes a claim that there is a law backing their argument, then there is no need for them to seek the consensus of the group.

If I have interpreted this correctly, I counter-propose that we close this issue with no further action.

I am strongly opposed to the proposal, because I think it's a waste of time that will not have any beneficial effect. 

As @dwsinger and I have noted there is no apparent question that we are bound by applicable law. 

If there is a specific proposal then we consider it on its merits. If one of its "merits" is that it breaches law we are bound to follow, then the discussion is likely to be short, and the outcome obvious. 

An attempt to implement a generic principle that doesn't match a specific requirement of a specific piece of law, but instead tries to codify some legal principle and apply it to our work, involves us trying to reframe the law in question. That is unnecessary but complex work. In any case a specific question needs to be judged against the actual law in question, not our reframing of it in our own words - which will generally be considered at least largely irrelevant in any legal determination.

**Comment by jwrosewell** [comment]
@mnot We need to consider the [World Trade Organization](https://www.wto.org/) ("WTO") and the [G7 and EU](https://en.wikipedia.org/wiki/G7) when assessing this.

WTO member states promote fair and open competition. Whilst much of the focus is on tariffs other factors are important. For example; state aid, and standards, among many others.

In addition to the WTO the G7 and EU are working closing on standards, particularly in digital.

The example you provide with XML and Vietnam is trivial. A stronger example might be data interoperability.

As an [independent digital expert with the CMA](https://www.gov.uk/government/publications/cma-independent-digital-experts-biographies/biographies-of-the-cmas-independent-digital-experts#mark-nottingham) you could ask the CMA for their position if you don't trust me.

If the US were to leave the G7 and WTO then the situation might be different.

**Comment by chaals** [comment]
@jrosewell, to repeat my question [from above](https://github.com/w3c/AB-public/issues/98#issuecomment-1622733520)

Do you propose a concrete question to answer, a concrete action you want us to take, or to make a presentation on your ideas expounded in this issue?

If you propose a presentation, I am strongly opposed since it seems you so far you have only offered generalities and there is no evidence you're going to be usefully consuming people's time.

If you want us to answer the question "should we follow relevant law" I think there is nobody who has argued otherwise and I believe it is a waste of time to discuss this.

If there is a specific action that would result in us following applicable law we currently don't, or if you have a different question, or can at least formulate what you are asking us to do in such a way that we can tell whether we have done it or not, please restate it.

As far as I understand, your entire input on this issue amounts to: "We need to follow the law. Please read lots of documents and, like, think about everything...".  With what seems a request to do unbounded work with no obvious improvement to anything as an outcome, I don't see any value in your proposal here. I suspect I am not the only one.

**Comment by TzviyaSiegman** [comment]
Agreed to close per discussion on 10/26/23 https://www.w3.org/2023/10/26-vision-minutes.html
